name: Trafik ETL

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"   # dagligen 00:00 UTC

permissions:
  contents: write

concurrency:
  group: trv-etl
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint (syntax/indent)
        run: python -tt -m compileall -q src

      - name: Run ETL to build trafik.db
        shell: bash
        env:
          PYTHONPATH: .
          TRAFIKVERKET_API_KEY: ${{ secrets.TRAFIKVERKET_API_KEY }}
          TRAFIKVERKET_URL: https://api.trafikinfo.trafikverket.se/v2/data.xml
        run: |
          set -euo pipefail
          python - <<'PY'
          from src.app.etl_runner import run_etl
          print(run_etl("trafik.db", days_back=30))
          PY
          test -f trafik.db || { echo "trafik.db missing"; exit 1; }

      - name: Commit & push (rebase-safe)
        shell: bash
        run: |
          set -euo pipefail

          # Bot-identitet
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          BRANCH="${GITHUB_REF_NAME:-main}"

          # Blanda in senaste remote-tip innan commit
          git fetch --prune origin "$BRANCH"
          git checkout -B "$BRANCH" "origin/$BRANCH"

          # Staga bara db-filen
          git add -f trafik.db

          # Commita bara om något ändrats
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "chore: update trafik.db [skip ci]"

          # Pusha säkert (skriver inte över nya commits på remote)
          git push --force-with-lease origin HEAD:"$BRANCH"
