name: Update trafik.db

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - ".github/workflows/trv-etl.yml"
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

concurrency:
  group: trv-etl
  cancel-in-progress: false

jobs:
  build-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint: compile Python (fail on syntax/indent)
        run: python -tt -m compileall -q src

      - name: Run ETL to build trafik.db
        shell: bash
        env:
          PYTHONPATH: .
          TRAFIKVERKET_API_KEY: ${{ secrets.TRAFIKVERKET_API_KEY }}
          TRAFIKVERKET_URL: https://api.trafikinfo.trafikverket.se/v2/data.xml
        run: |
          set -euo pipefail
          python - <<'PY'
from src.app.etl_runner import run_etl
print(run_etl("trafik.db", days_back=1))
PY
          test -f trafik.db || { echo "trafik.db missing"; exit 1; }

      - name: Commit & push if changed
        run: |
          if git status --porcelain | grep -q "trafik.db"; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add trafik.db
            git commit -m "chore: update trafik.db"
            git push
          else
            echo "No changes in trafik.db"
          fi
